using Unity.Entities;
using Unity.Mathematics;

namespace PureDOTS.Runtime.AI
{
    /// <summary>
    /// High-level villager goals shared across games.
    /// </summary>
    public enum VillagerGoal : byte
    {
        Idle = 0,
        Work = 1,
        Eat = 2,
        Sleep = 3,
        SeekShelter = 4,
        Pray = 5,
        Socialize = 6,
        Flee = 7
    }

    /// <summary>
    /// Current/previous villager goal plus urgency metadata.
    /// </summary>
    public struct VillagerGoalState : IComponentData
    {
        public VillagerGoal CurrentGoal;
        public VillagerGoal PreviousGoal;
        public uint LastGoalChangeTick;
        public float CurrentGoalUrgency;
    }

    /// <summary>
    /// Normalized (0-1) urgent need values generated by the mind pipeline.
    /// </summary>
    public struct VillagerNeedState : IComponentData
    {
        public float HungerUrgency;
        public float RestUrgency;
        public float FaithUrgency;
        public float SafetyUrgency;
        public float SocialUrgency;
        public float WorkUrgency;

        public readonly float MaxUrgency()
        {
            var maxA = math.max(HungerUrgency, RestUrgency);
            var maxB = math.max(FaithUrgency, SafetyUrgency);
            var maxC = math.max(SocialUrgency, WorkUrgency);
            return math.max(maxA, math.max(maxB, maxC));
        }
    }

    /// <summary>
    /// Per-agent tuning for need decay/pressure.
    /// </summary>
    public struct VillagerNeedTuning : IComponentData
    {
        public float HungerDecayPerTick;
        public float RestDecayPerTick;
        public float FaithDecayPerTick;
        public float SafetyDecayPerTick;
        public float SocialDecayPerTick;
        public float WorkPressurePerTick;
        public float MaxUrgency;
    }

    /// <summary>
    /// Cadence override used by intent bridge systems to throttle updates per villager.
    /// </summary>
    public struct VillagerMindCadence : IComponentData
    {
        public int CadenceTicks;
        public uint LastRunTick;
    }

    /// <summary>
    /// Output from threat evaluators that request immediate flee steering.
    /// </summary>
    public struct VillagerFleeIntent : IComponentData
    {
        public float3 ExitDirection;
        public float Urgency;
    }

    /// <summary>
    /// Tracks the most recent threat seen by a villager.
    /// </summary>
    public struct VillagerThreatState : IComponentData
    {
        public Entity ThreatEntity;
        public float3 ThreatDirection;
        public float Urgency;
        public byte HasLineOfSight;
    }
}
